print("welcome to my band name crew")
input("what city did you grow up")
print ('input("what city did you grow up")'')
input("what is your pet's name")
print(input("what is your pet's name"))
name = input("what city did you grow up")
petname = input ("what is your pet's name")
bandname = (name + petname)
print("bandname")